### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by masterchop** [cxjyxxme/deep-online-video-stabilization-deploy#3]
i dont see how to use it for a vid

**Comment by ishank-juneja** [comment]
Hi @masterchop,

I was able to deploy and use the code, the instructions given in the Readme are sufficient, Were you able to make it work later?

**Comment by ishank-juneja** [comment]
See the pull request #7 for stabilization of an unstable video with no stable reference available

**Comment by masterchop** [comment]
I am sorry, i had to drop this and use another tool. i will try to comeback.
Thank you for your efforts to help me , i do appreciate them.
