### ISSUE TITLE
How to run with only "unstable" data

### ISSUE THREAD

**Issue by brettwooldridge** [cxjyxxme/deep-online-video-stabilization-deploy#5]
I am trying to stabilize a video.  I have created a structure like:
```
datas
   Video0
      list.txt
      stable (empty)
      unstable
         0.avi
```
Meaning, of course, that have no *stable* version of the video, only an unstable version.

When I execute the ``deploy_bundle.py`` script, I get an error.  Specifically, I am executing the command:
```
python3 -u deploy_bundle.py --model-dir ./models/v2_93/ --model-name model-90000 --before-ch 31 \
   --deploy-vis --gpu_memory_fraction 0.9 --output-dir ./output/v2_93/Video0  \
   --test-list datas/Video0/list.txt --prefix datas/Video0;
```
I get the following error:
```
(python3:10): GStreamer-CRITICAL **: 22:13:06.423: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed
[ WARN:0] global /usr/local/src/opencv/modules/videoio/src/cap_gstreamer.cpp (713) open OpenCV | GStreamer warning: Error opening bin: no element "datas"
[ WARN:0] global /usr/local/src/opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```
Looking at the code, it seems that the code is predicated on being able to [open a stable version of the video](https://github.com/cxjyxxme/deep-online-video-stabilization-deploy/blob/master/deploy_bundle.py#L188).

**Comment by ishank-juneja** [comment]
@brettwooldridge I recently created a pull request #7 that allows for stabilization without a reference video. Yourself or others coming here could consider checking it out.

**Comment by ishank-juneja** [comment]
@cxjyxxme this issue can be closed now
